# @package _global_
training:
  batch_size: 16
  lr: 0.005
  epochs: 30
  num_workers: 2
  # Where to save the best checkpoint (by validation accuracy)
  checkpoint_path: ${hydra:runtime.cwd}/best_model_cnn_baseline.pt
  device: cuda
